# 1. Numpy

# 1) 다차원 배열 클래스

In [7]:
import numpy as np

In [20]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([[1, 2, 3],[4, 5, 6]])
c = np.array(["Hello", "Python", "World"])

print(a)
print(type(a))
print(b)
print(type(b))
print(c)
print(type(c))

print("shape :", a.shape)
print("shape :", b.shape)
print("shape :", c.shape)
print("---------------------")
print("ndim :", a.ndim)
print("ndim :", b.ndim)
print("ndim :", c.ndim)
print("---------------------")
print("dtype :", a.dtype)
print("dtype :", b.dtype)
print("dtype :", c.dtype)
print("---------------------")
print("itemsize :", a.itemsize)
print("itemsize :", b.itemsize)
print("itemsize :", c.itemsize)
print("---------------------")
print("size :", a.size)
print("size :", b.size)
print("size :", c.size)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
['Hello' 'Python' 'World']
<class 'numpy.ndarray'>
shape : (5,)
shape : (2, 3)
shape : (3,)
---------------------
ndim : 1
ndim : 2
ndim : 1
---------------------
dtype : int32
dtype : int32
dtype : <U6
---------------------
itemsize : 4
itemsize : 4
itemsize : 24
---------------------
size : 5
size : 6
size : 3


# 2) 주요 메소드 / 함수

In [19]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([[1, 2, 3],[4, 5, 6]])

print(a.max())
print(a.min())
print(a.mean())
print(b.flatten())

5
1
3.0
[1 2 3 4 5 6]


In [35]:
a = np.array([1, 2, 3])
b = np.array([[4, 5, 6,],[7, 8, 9]])
c = np.array([[10, 11, 12],[13, 14, 15]])

print(np.append(a, b))
print("----------------------")
print(np.append([a], b, axis=0))
print("----------------------")
print(np.append(b, c, axis=0))
print("----------------------")
print(np.append(b, c, axis=1))

[1 2 3 4 5 6 7 8 9]
----------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------------
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
----------------------
[[ 4  5  6 10 11 12]
 [ 7  8  9 13 14 15]]


In [38]:
a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6],[7, 8]])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)
print("------------------")
#행렬곱
print(a@b)
print(np.matmul(a,b))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[    1    64]
 [ 2187 65536]]
------------------
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


# 3) ndarray 생성 함수

In [44]:
print(np.zeros((3,3)))
print(np.ones((3,3)))
print(np.full((3,3),10))
print(np.eye(3))
print(np.arange(0, 10, 2))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]


In [46]:
a = np.arange(15)
print(np.arange(15))
print(a)
print("-----------------")
b = a.reshape(3,5)
print(np.arange(15).reshape(3,5))
print(b)
print("-----------------")
c = b.transpose()
print(np.arange(15).reshape(3,5).transpose())
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
-----------------
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-----------------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


# 4) 다차원 배열의 축

In [47]:
a = np.arange(1,7).reshape(3,2)
print(a.sum())
print(a.sum(axis = 0))
print(a.sum(axis = 1))

21
[ 9 12]
[ 3  7 11]


In [54]:
a = np.arange(1,7).reshape(3,2)
print(a)
print("----------------")
print(np.insert(a, 1, 10))
print(np.insert(a, 1, 10, axis=0))
print(np.insert(a, 1, 10, axis=1))
print("----------------")
print(np.delete(a, 1, axis = 0))
print(np.delete(a, 1, axis = 1))

[[1 2]
 [3 4]
 [5 6]]
----------------
[ 1 10  2  3  4  5  6]
[[ 1  2]
 [10 10]
 [ 3  4]
 [ 5  6]]
[[ 1 10  2]
 [ 3 10  4]
 [ 5 10  6]]
----------------
[[1 2]
 [5 6]]
[[1]
 [3]
 [5]]


# 5) 인덱싱과 슬라이싱

In [59]:
a = np.arange(0,5)
print(a)
print(a[0], a[3], a[-1])
print(a[[0, 3, -1]])  # numpy only

[0 1 2 3 4]
0 3 4
[0 3 4]


In [61]:
a = np.arange(0,10)
print(a)

print("------------------------")
print(a[:3])
print(a[3:7])
print(a[::2])
print(a[::-1])

[0 1 2 3 4 5 6 7 8 9]
------------------------
[0 1 2]
[3 4 5 6]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


In [65]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)

print("------------------------")
print(a[0][1])
print(a[2][1])
print("------------------------")
print(a[0,1])
print(a[2,1])

[[1 2]
 [3 4]
 [5 6]]
------------------------
2
6
------------------------
2
6


In [71]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)

print("------------------------")
print(a[:2])
print("------------------------")
print(a[:2][1])
print(a[:2, 1])
print("------------------------")
print(a[:2][1][1])

[[1 2]
 [3 4]
 [5 6]]
------------------------
[[1 2]
 [3 4]]
------------------------
[3 4]
[2 4]
------------------------
4
